baseURL = "http://hugo-deploy-bucket.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "Hugo website via AWS Cloud9"
theme = "ananke1"

[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://hugo-deploy-bucket/?region=us-east-1" #your bucket here